### PR TITLE
Added Proxy support.

### PR DESCRIPTION
**Pull request by ayush-vlocity**
Added support to use proxy to request. For Anonymous User.
@haxaco

### CODE REVIEW

**Comment by haxaco** [comment]
LGTM @ayush-vlocity 
@jaan @mattgoldspink  heads up

**Review by mattgoldspink — COMMENTED** [review]
Looks good to me

**Comment by jaan** [comment]
LGTM

**Comment by frankyanwang** [comment]
It is very hard to see the diff (I tried side by side and merged view), is it because the space issue?  You change seem to be small but I cannot clearly see what's the change.

**Comment by frankvlocity** [comment]
It is very hard to see the diff (I tried side by side and merged view), is it because the space issue? You change seem to be small but I cannot clearly see what's the change. Can you please fix it?

**Comment by haxaco** [comment]
@frankvlocity you can set up the diff to be side by side and ignore the whitespace, I attached a screenshot of the changes which are the inclusion fo the visualforce variable and setting the useProxy url. ForceNG was requiring us to have a sessionId for all calls, which in the case for a unauthenticated user they wont have a sessionId.

screen shot 2018-07-15 at 4 48 17 pm

**Comment by haxaco** [comment]
@frankvlocity please review this PR this week when possible, we want to get this in for CMT 103 and make sure that we test it thoroughly

**Comment by frankvlocity** [comment]
Ok I will merge in to our develop branch and do some test.

**Pull request merged**
